"""Create messages table

Revision ID: 9b85e4d4da22
Revises: 8f2cc7e1c178
Create Date: 2024-10-23 10:46:09.819229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b85e4d4da22'
down_revision = '8f2cc7e1c178'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
